# Data Keystone: Exploring the Dataset

## Loading the Dataset

In [22]:
import pandas as pd

df = pd.read_csv('steam_games_dataset.csv')

## Exploring the Dataset Structure

In [23]:
print(df.head())
print(df.info())
print(df.shape)
df.columns
df.dtypes

     appid                              name         developer  \
0      730  Counter-Strike: Global Offensive             Valve
1  1172470                      Apex Legends           Respawn
2   578080               PUBG: BATTLEGROUNDS  PUBG Corporation
3  1623730                          Palworld        Pocketpair
4      440                   Team Fortress 2             Valve

         publisher  score_rank  positive  negative  userscore  \
0            Valve         NaN   7642084   1173003          0
1  Electronic Arts         NaN    668053    326926          0
2    KRAFTON, Inc.         NaN   1520457   1037487          0
3       Pocketpair         NaN    358266     22443          0
4            Valve         NaN   1044264    117208          0

                       owners  average_forever  average_2weeks  \
0  100,000,000 .. 200,000,000            33852             708
1  100,000,000 .. 200,000,000            10506             496
2  100,000,000 .. 200,000,000            23165             717
3   50,000,000 .. 100,000,000             3854             835
4   50,000,000 .. 100,000,000            21244             736

   median_forever  median_2weeks  price  initialprice  discount      ccu
0            6645            301      0             0         0  1013936
1             935            246      0             0         0   124262
2            5622            261      0             0         0   314682
3            2213            257   2999          2999         0    18028
4            4262            102      0             0         0    43819
<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 17 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   appid            10000 non-null  int64
 1   name             10000 non-null  str
 2   developer        9967 non-null   str
 3   publisher        9946 non-null   str
 4   score_rank       5 non-null      float64
 5   positive         10000 non-null  int64
 6   negative         10000 non-null  int64
 7   userscore        10000 non-null  int64
 8   owners           10000 non-null  str
 9   average_forever  10000 non-null  int64
 10  average_2weeks   10000 non-null  int64
 11  median_forever   10000 non-null  int64
 12  median_2weeks    10000 non-null  int64
 13  price            10000 non-null  int64
 14  initialprice     10000 non-null  int64
 15  discount         10000 non-null  int64
 16  ccu              10000 non-null  int64
dtypes: float64(1), int64(12), str(4)
memory usage: 1.3 MB
None
(10000, 17)

appid                int64
name                   str
developer              str
publisher              str
score_rank         float64
positive             int64
negative             int64
userscore            int64
owners                 str
average_forever      int64
average_2weeks       int64
median_forever       int64
median_2weeks        int64
price                int64
initialprice         int64
discount             int64
ccu                  int64
dtype: object

## Exploring Column Values

In [24]:
print(df.value_counts())
print(df.describe())

appid   name                            developer                 publisher                score_rank  positive  negative  userscore  owners                average_forever  average_2weeks  median_forever  median_2weeks  price  initialprice  discount  ccu
22490   Fallout: New Vegas              Obsidian Entertainment    Bethesda Softworks       100.0       46753     2153      95         500,000 .. 1,000,000  3333             379             1409            310            999    999           0         318    1
790650  MARVEL END TIME ARENA           Smilegate Entertainment   Smilegate Entertainment  99.0        368       160       69         100,000 .. 200,000    158              0               158             0              0      0             0         0      1
907680  Wwbit                           1bit                      1bit                     98.0        710       566       55         100,000 .. 200,000    23               0               19              0              0      0             0         0      1
823550  Booty Calls                     3X Entertainment Limited  Nutaku Publishing        98.0        255       294       46         100,000 .. 200,000    272              0               131             0              0      0             0         33     1
639780  Deep Space Waifu: FLAT JUSTICE  Neko Climax Studios       Neko Climax Studios      100.0       1449      67        95         50,000 .. 100,000     137              0               111             0              399    399           0         0      1
Name: count, dtype: int64
              appid  score_rank      positive      negative     userscore  \
count  1.000000e+04         5.0  1.000000e+04  1.000000e+04  10000.000000
mean   9.008700e+05        99.0  1.214202e+04  1.948096e+03      0.036000
std    7.290494e+05         1.0  9.536926e+04  1.812977e+04      1.671581
min    1.000000e+01        98.0  0.000000e+00  0.000000e+00      0.000000
25%    3.365875e+05        98.0  4.310000e+02  1.100000e+02      0.000000
50%    6.551300e+05        99.0  1.514500e+03  2.950000e+02      0.000000
75%    1.333238e+06       100.0  4.996750e+03  8.712500e+02      0.000000
max    3.605460e+06       100.0  7.642084e+06  1.173003e+06     95.000000

       average_forever  average_2weeks  median_forever  median_2weeks  \
count     10000.000000    10000.000000    10000.000000   10000.000000
mean       1023.689500      112.496300      515.001700     118.949000
std        4193.287962      638.473189     3508.429257     707.962801
min           0.000000        0.000000        0.000000       0.000000
25%         145.000000        0.000000       79.750000       0.000000
50%         310.000000        0.000000      210.000000       0.000000
75%         817.250000        6.000000      406.000000       6.000000
max      263340.000000    20080.000000   269193.000000   20080.000000

              price  initialprice      discount           ccu
count  10000.000000  10000.000000  10000.000000  1.000000e+04
mean    1131.326700   1284.141500      8.675800  5.643178e+02
std     1299.903805   1364.327698     23.476133  1.128781e+04
min        0.000000      0.000000      0.000000  0.000000e+00
25%       99.000000    199.000000      0.000000  0.000000e+00
50%      719.000000    999.000000      0.000000  5.000000e+00
75%     1799.000000   1999.000000      0.000000  4.500000e+01
max    14999.000000  14999.000000     95.000000  1.013936e+06

The values of the 'appid' column are in exponential notation, which provides little value on its own. Steam is a massive platform, but surely the ids can't be that large.

In [25]:
df['appid'].max()

np.int64(3605460)

The maximum value from the 'appid' column is on 7 digits long, but it is stored as an int64. That feels excessive.

In [26]:
df = df.astype({'appid': 'int32'})
print(df.dtypes)

appid                int32
name                   str
developer              str
publisher              str
score_rank         float64
positive             int64
negative             int64
userscore            int64
owners                 str
average_forever      int64
average_2weeks       int64
median_forever       int64
median_2weeks        int64
price                int64
initialprice         int64
discount             int64
ccu                  int64
dtype: object

In [29]:
df.head()
df.describe()

,appid,score_rank,positive,negative,userscore,average_forever,average_2weeks,median_forever,median_2weeks,price,initialprice,discount,ccu
count,1.000000e+04,5.0,1.000000e+04,1.000000e+04,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,1.000000e+04
mean,9.008700e+05,99.0,1.214202e+04,1.948096e+03,0.036000,1023.689500,112.496300,515.001700,118.949000,1131.326700,1284.141500,8.675800,5.643178e+02
std,7.290494e+05,1.0,9.536926e+04,1.812977e+04,1.671581,4193.287962,638.473189,3508.429257,707.962801,1299.903805,1364.327698,23.476133,1.128781e+04
min,1.000000e+01,98.0,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00
25%,3.365875e+05,98.0,4.310000e+02,1.100000e+02,0.000000,145.000000,0.000000,79.750000,0.000000,99.000000,199.000000,0.000000,0.000000e+00
50%,6.551300e+05,99.0,1.514500e+03,2.950000e+02,0.000000,310.000000,0.000000,210.000000,0.000000,719.000000,999.000000,0.000000,5.000000e+00
75%,1.333238e+06,100.0,4.996750e+03,8.712500e+02,0.000000,817.250000,6.000000,406.000000,6.000000,1799.000000,1999.000000,0.000000,4.500000e+01
max,3.605460e+06,100.0,7.642084e+06,1.173003e+06,95.000000,263340.000000,20080.000000,269193.000000,20080.000000,14999.000000,14999.000000,95.000000,1.013936e+06

Okay, changing the dtype didn't fix the notation issue... Online research suggests the only way to adjust it is to change a global pandas setting for trailing zeros on a float. Not ideal, so we'll let the describe nuance go. That being said, more of these column dtypes likely don't need int64. Let's adjust those further.

In [ ]:
# Convert dtypes from int64 to smaller increments here

## Practicing Basic Cleaning and Wrangling

In [28]:
df[df['score_rank'] == 100.0]

,appid,name,developer,publisher,score_rank,positive,negative,userscore,owners,average_forever,average_2weeks,median_forever,median_2weeks,price,initialprice,discount,ccu
2122,22490,Fallout: New Vegas,Obsidian Entertainment,Bethesda Softworks,100.0,46753,2153,95,"500,000 .. 1,000,000",3333,379,1409,310,999,999,0,318
9662,639780,Deep Space Waifu: FLAT JUSTICE,Neko Climax Studios,Neko Climax Studios,100.0,1449,67,95,"50,000 .. 100,000",137,0,111,0,399,399,0,0